@echo on
del *.aux
del *.toc
del *.lof
del *.lot
del *.ilg
del *.idx
del *.ind
del *.out
del *.log
del *.exa
del *.thm
del *.bbl
del *.blg
del *.gz
del *.bak
del  *.nav
del  *.snm
del Sections\*.aux
del Sections\*.bak
del Sections\*.aux
del Sections\*.toc
del Sections\*.lof
del Sections\*.lot
del Sections\*.ilg
del Sections\*.idx
del Sections\*.ind
del Sections\*.out
del Sections\*.log
del Sections\*.exa
del Sections\*.thm
del Sections\*.bbl
del Sections\*.blg
del Sections\*.gz
del Sections\*.bak
del  Sections\*.nav
del  Sections\*.snm

@pause

@echo on
